name: Code Changes

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/reusable_lint.yaml

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    uses: ./.github/workflows/reusable_test.yaml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # Install without rpy2 for documentation build
          pip install -e .
          pip install pytest pytest-cov black isort flake8 mypy jupyter-book yaml-changelog build setuptools wheel codecov
      
      - name: Build documentation
        run: |
          cd docs
          jupyter-book build .
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html