name: Lint

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.4"
          enable-cache: false
      
      - name: Install dependencies
        run: |
          uv venv
          uv pip install --upgrade black
      
      - name: Check formatting
        run: |
          source .venv/bin/activate
          black . -l 79 --check