name: Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true  
        type: string

jobs:
  test:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.4"
          enable-cache: false
      
      - name: Install package with dev dependencies (Unix)
        if: runner.os != 'Windows'
        run: |
          uv venv
          source .venv/bin/activate
          # Install without rpy2 for CI tests
          uv pip install -e .
          uv pip install pytest pytest-cov black isort flake8 mypy jupyter-book yaml-changelog build setuptools wheel codecov
      
      - name: Install package with dev dependencies (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          uv venv
          call .venv\Scripts\activate
          REM Install without rpy2 for CI tests
          uv pip install -e .
          uv pip install pytest pytest-cov black isort flake8 mypy jupyter-book yaml-changelog build setuptools wheel codecov
      
      - name: Run tests (Unix)
        if: runner.os != 'Windows'
        run: |
          source .venv/bin/activate
          # Skip R comparison tests in CI
          pytest tests/ -v --cov=statmatch --cov-report=xml -k "not against_r"
      
      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          call .venv\Scripts\activate
          REM Skip R comparison tests in CI
          pytest tests/ -v --cov=statmatch --cov-report=xml -k "not against_r"
      
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: inputs.os == 'ubuntu-latest' && inputs.python-version == '3.12'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false