name: Test

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true  
        type: string

jobs:
  test:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.4"
          enable-cache: false
      
      - name: Install package with dev dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"
      
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/ -v --cov=statmatch --cov-report=xml
      
      - name: Upload coverage
        uses: codecov/codecov-action@v4
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true